export const GET_ALL_PERSONS = "GET_ALL_PERSONS";
export const GET_PERSON_BY_ATRIB = "GET_PERSON_BY_ATRIB";
export const CHANGE_ATTRIB = "CHANGE_ATTRIB";
export const CHANGE_PAGINA = "CHANGE_PAGINA";
export const GET_PERSON_BY_LIMIT = "GET_PERSON_BY_LIMIT";
export const RESET_ULT_DOC = "RESET_ULT_DOC";
